### ISSUE TITLE
Use the async and defer parameters in the script tags

### ISSUE THREAD

**Issue by hermes85pl** [abinnovision/recaptcha-v3#354]
Although the [docs for v3](https://developers.google.com/recaptcha/docs/v3) do not mention this, you should use `async` and `defer` parameters in the `script` tags the same way as it is [described for v2](https://developers.google.com/recaptcha/docs/display). By not doing so you make the page load longer, and in case of a simple page it is many times longer than it could be.

**Comment by nestle49** [comment]
Any news?

**Comment by hermes85pl** [comment]
How about a release with the fix? I can see that [some changes to the source code have been made](https://github.com/abinnovision/recaptcha-v3/commit/8d6fe8e7086a02cb64d7bad0fa0fe6dc3f6d2956), yet they don't appear to be published. I wonder if perhaps @WipeAir has any plans for this.

**Comment by nestle49** [comment]
> How about a release with the fix? I can see that [some changes to the source code have been made](https://github.com/abinnovision/recaptcha-v3/commit/8d6fe8e7086a02cb64d7bad0fa0fe6dc3f6d2956), yet they don't appear to be published. I wonder if perhaps @WipeAir has any plans for this.

He does not answer. Looks like the package is no longer supported

**Comment by WipeAir** [comment]
Released with v1.11.1.
