### ISSUE TITLE
Render parameter "theme" is possibly not supported

### ISSUE THREAD

**Issue by artshade** [abinnovision/recaptcha-v3#936]
Dear Developers,

Thank you for the awesome solution!

Apparently, the [`theme`](<https://developers.google.com/recaptcha/docs/display#render_param>) render parameter is not supported by the library. Is that correct?

https://github.com/abinnovision/recaptcha-v3/blob/879657a66222d14f6c1d63c28456d9aaa8dfce98/src/ReCaptchaLoader.ts#L299-L304

How would you set `data-theme` attribute or `render` function parameter in such case to have it `rc-anchor-dark` in the `iframe` in such case?

Best and kind regards

**Comment by WipeAir** [comment]
This has been added in version 1.11.2.
You can now define the `theme` property in the `explicitRenderParameters` on the `load` function.
